### ISSUE TITLE
h1 should be small 

### ISSUE THREAD

**Issue by olavea** [queen-raae/pow-site#22]
the h1 is small in old, big in new

![pow-h1](https://github.com/user-attachments/assets/ec765831-ac2b-4016-8b54-592d33c8975d)

**Comment by raae** [comment]
You can do `class="prose-h1:text-base"` see https://github.com/tailwindlabs/tailwindcss-typography?tab=readme-ov-file#element-modifiers

**Comment by olavea** [comment]
I changed to this:
`<article class="prose prose-h1:text-xl ....>`

from this:
this:
`<article` class="prose prose-h1:text-5xl ....>`
